name = "pesde/toolchainlib"
version = "0.1.7"
description = "A Luau library for implementing toolchain management"
license = "MIT"
repository = "https://github.com/pesde-pkg/tooling/tree/main/toolchainlib"
private = false
includes = ["src", "pesde.toml", "LICENSE", "README.md"]

[target]
environment = "lune"
lib = "src/init.luau"

[dependencies.dirs]
name = "jiwonz/dirs"
version = "^0.1.1"
index = "https://github.com/daimond113/pesde-index"

[dependencies.pathfs]
name = "jiwonz/pathfs"
version = "^0.1.0"
index = "https://github.com/daimond113/pesde-index"

[peer_dependencies.option]
name = "lukadev_0/option"
version = "^1.2.0"
index = "https://github.com/daimond113/pesde-index"

[peer_dependencies.result]
name = "lukadev_0/result"
version = "^1.2.0"
index = "https://github.com/daimond113/pesde-index"
